#!/usr/bin/env bash
# hermes-codex-loop setup check — 10-second health check.
# Run: bash scripts/check-setup.sh
# Prints ✅/❌ per prerequisite so you know exactly what's missing.

set -u
PASS=0; FAIL=0

ok()   { PASS=$((PASS+1)); printf "  ✅ %s\n" "$1"; }
bad()  { FAIL=$((FAIL+1)); printf "  ❌ %s\n" "$1"; }

echo "== hermes-codex-loop setup check =="
echo

# 1. Codex CLI
echo "[1/6] Codex CLI"
CODEX_BIN="${CODEX_BIN:-}"
if [ -z "$CODEX_BIN" ]; then
  CODEX_BIN="$(command -v codex 2>/dev/null || echo '')"
fi
if [ -z "$CODEX_BIN" ]; then
  bad "codex CLI not found (set CODEX_BIN or add codex to PATH)"
else
  VER="$("$CODEX_BIN" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
  if [ -n "$VER" ]; then
    MAJOR="$(echo "$VER" | cut -d. -f1)"
    MINOR="$(echo "$VER" | cut -d. -f2)"
    if [ "$MAJOR" -gt 0 ] || [ "$MINOR" -ge 146 ]; then
      ok "codex $VER at $CODEX_BIN"
    else
      bad "codex $VER is too old — need >= 0.146 ($CODEX_BIN)"
    fi
  else
    bad "codex --version failed at $CODEX_BIN"
  fi
fi
echo

# 2. ~/.codex/config.toml — deepseek provider
echo "[2/6] ~/.codex/config.toml → [model_providers.deepseek]"
CFG="${CODEX_HOME:-$HOME/.codex}/config.toml"
if [ ! -f "$CFG" ]; then
  bad "config.toml not found at $CFG"
elif grep -q 'model_providers.deepseek' "$CFG"; then
  if grep -q 'wire_api = "responses"' "$CFG"; then
    ok "deepseek provider with responses wire API"
  else
    bad "deepseek provider exists but wire_api is not \"responses\""
  fi
  if grep -q 'env_key = "DEEPSEEK_API_KEY"' "$CFG"; then
    ok "key via env_key (no token on disk)"
  else
    bad "env_key missing — check for leftover experimental_bearer_token placeholder"
  fi
else
  bad "no [model_providers.deepseek] — run DeepSeek's one-click setup script"
fi
echo

# 3. models.json
echo "[3/6] ~/.codex/models.json"
MODELS="${CODEX_HOME:-$HOME/.codex}/models.json"
if [ ! -f "$MODELS" ]; then
  bad "models.json not found — generated by DeepSeek's setup script"
elif grep -q 'deepseek-v4-flash' "$MODELS"; then
  ok "models.json declares deepseek-v4-flash"
else
  bad "models.json exists but lacks deepseek-v4-flash"
fi
echo

# 4. API key
echo "[4/6] DEEPSEEK_API_KEY"
KEY="$(env | grep -E '^DEEPSEEK_API_KEY=' | cut -d= -f2-)"
if [ -z "$KEY" ]; then
  for f in "${HERMES_HOME:-$HOME/.hermes}/.env" "$HOME/.hermes/.env" ".env"; do
    [ -f "$f" ] && KEY="$(grep -E '^DEEPSEEK_API_KEY=' "$f" 2>/dev/null | head -1 | cut -d= -f2-)"
    [ -n "$KEY" ] && break
  done
fi
if [ -n "$KEY" ]; then
  ok "DEEPSEEK_API_KEY available (${#KEY} chars, not shown)"
else
  bad "DEEPSEEK_API_KEY missing (env, ~/.hermes/.env, or HERMES_ENV_FILE)"
fi
echo

# 5. Hermes version
echo "[5/6] Hermes Agent"
HERMES="${HERMES_BIN:-$(command -v hermes 2>/dev/null || echo '')}"
if [ -z "$HERMES" ]; then
  bad "hermes CLI not found on PATH"
else
  HVER="$("$HERMES" --version 2>/dev/null | grep -oE 'v[0-9]+\.[0-9]+' | head -1)"
  if [ -n "$HVER" ]; then
    ok "hermes $HVER at $HERMES"
  else
    bad "hermes --version failed at $HERMES"
  fi
fi
echo

# 6. Plugin installed
echo "[6/6] Plugin in Hermes plugins dir"
PLUGINS="${HERMES_PLUGINS_DIR:-}"
if [ -z "$PLUGINS" ]; then
  PLUGINS="${HERMES_HOME:-$HOME/.hermes}/plugins"
  [ -d "$HOME/.hermes/plugins" ] || PLUGINS="$PLUGINS"
fi
if find "$PLUGINS" -maxdepth 1 -name "*codex*" -o -maxdepth 1 -name "*hermes-codex*" 2>/dev/null | grep -q .; then
  ok "plugin found under $PLUGINS"
else
  bad "plugin not found — copy this repo into $PLUGINS/"
fi
echo

echo "=============================="
echo "  $PASS passed, $FAIL failed"
echo "=============================="
[ "$FAIL" -eq 0 ] && echo "  ✅ All good — restart Hermes and use the codex tool." || echo "  ❌ Fix the items above, then re-run this script."
